### ISSUE TITLE
please apk  v1.1.0

### ISSUE THREAD

**Issue by madrid2022ok** [PlanetVormir/BartonTV#1]
please apk android tv v1.1.0 thanks you friend  year 2023

**Comment by madrid2022ok** [comment]
please i version ipa tvos bartontv 
 please  version ipa ios bartontv

**Comment by sujaldev** [comment]
Hey! Sorry I wasn't able to publish the latest APK but it doesn't matter now as the API doesn't work anymore, please find another project.
